feature: custom certificate support
quay/openshift-mirror-registry pull request #6
Opened 2021-10-14 19:48 UTC by pbertera

This PR implements the `--sslCert` and `--sslKey` command line options allowing to define a custom certificate for Quay

2021-12-10 21:33 UTC, HammerMeetNail commented on cmd/install.go
> +	sslCertAbs, err := filepath.Abs(sslCert)
Indentation looks a little off here. Would you mind fixing before merge?

2021-12-10 21:35 UTC, HammerMeetNail commented on cmd/install.go
> +		sslCertKeyFlag + // optional ssl cert/key flag
Similar request here, for consistency can the whitespace between `sslCertKeyFlag` and the `+` be removed?

2021-12-10 21:41 UTC, HammerMeetNail requested changes
@pbertera Thanks for submitting this. I think the PR looks good, but would like to run it through CI. I've updated the target branch to be `quay:PROJQUAY-2247`, once we merge this it should trigger CI. If CI looks good, we can merge to `quay:master`. 

There were a couple formatting things I saw. Would you mind addressing those and rebasing or squashing the commits and then we'll merge to CI?

2021-12-13 09:44 UTC, pbertera commented
@HammerMeetNail thanks for the review and for the catch, I pushed the requested changes

2021-12-13 13:31 UTC, merged